services:
    app_bundle_storage_session:
       class: AppBundle\Services\SessionStorage
       arguments: [ @session ]

    app_bundle_storage_mongodb:
       class: AppBundle\Services\MongoDBStorage
       arguments: [ %database% ]
